language: go
sudo: required
dist: xenial
os:
  - linux
go:
  - "1.13"
install:
  - pwd
before_script:
  - pwd
  - currpath=`pwd`
    srcpath=${currpath%/src*}
  - export GOPATH=${currpath}:$GOPATH
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
 # - BUILD_TYPE=release
script:
  - cd src/main
  - go build -buildmode=plugin ../mrapps/wc.go
  - rm mr-out*
  - go run mrsequential.go wc.so pg*.txt
#  - more mr-out-0
  - go build -buildmode=plugin ../mrapps/wc.go
  - rm mr-out*
  - go run mrmaster.go pg-*.txt
#  - go run mrworker.go wc.so
